x-connection-params: &connection-params
  DATABASE_HOST: "main-db"
  DATABASE_USER: "svck"
  DATABASE_PASSWORD: "Password123"
  REDIS_URL: "redis://cache:6379"

x-rails-env: &rails-env
  RAILS_MASTER_KEY: $RAILS_MASTER_KEY
  <<: *connection-params

x-rails-app: &rails-app
  build:
    context: .
    dockerfile: Dockerfile.dev
  image: reg.staging.svck.dev/svck/aads_test:dev-build
  environment:
    RAILS_ENV: development
    <<: *rails-env
  tty: true
  stdin_open: true
  volumes:
    - .:/rails
    - /rails/node_modules
  depends_on:
    - main-db
    - cache


services:
  web:
    <<: *rails-app
    command: |
      sh -c "rm -f tmp/pids/server.pid; bundle install; bundle exec rails db:prepare; bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"

  sidekiq:
    <<: *rails-app
    command: |
      sh -c "bundle install; bundle exec sidekiq"

  test:
    <<: *rails-app
    environment:
      RAILS_ENV: test
      <<: *rails-env
    depends_on:
      - main-db
      - cache
    command: |
      sh -c "bundle install; sh"

  main-db:
    image: postgres:16.2-alpine3.19
    restart: on-failure
    healthcheck:
      test: "pg_isready -U svck"
    environment:
      POSTGRES_DB: svck
      POSTGRES_USER: svck
      POSTGRES_PASSWORD: "Password123"
    volumes:
      - main-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    image: eqalpha/keydb #redis:6.2.6-alpine3.14
    restart: on-failure
    healthcheck:
      test: "keydb-cli ping"
#    ports:
#      - "6379:6379"

volumes:
  main-db-data: