# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/dashboard/posts', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Dashboard::Post. As you add validations to Dashboard::Post, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Dashboard::Post.create! valid_attributes
      get dashboard_posts_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      post = Dashboard::Post.create! valid_attributes
      get dashboard_post_url(post)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_dashboard_post_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      post = Dashboard::Post.create! valid_attributes
      get edit_dashboard_post_url(post)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Dashboard::Post' do
        expect do
          post dashboard_posts_url, params: { dashboard_post: valid_attributes }
        end.to change(Dashboard::Post, :count).by(1)
      end

      it 'redirects to the created dashboard_post' do
        post dashboard_posts_url, params: { dashboard_post: valid_attributes }
        expect(response).to redirect_to(dashboard_post_url(Dashboard::Post.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Dashboard::Post' do
        expect do
          post dashboard_posts_url, params: { dashboard_post: invalid_attributes }
        end.not_to change(Dashboard::Post, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post dashboard_posts_url, params: { dashboard_post: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested dashboard_post' do
        post = Dashboard::Post.create! valid_attributes
        patch dashboard_post_url(post), params: { dashboard_post: new_attributes }
        post.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the dashboard_post' do
        post = Dashboard::Post.create! valid_attributes
        patch dashboard_post_url(post), params: { dashboard_post: new_attributes }
        post.reload
        expect(response).to redirect_to(dashboard_post_url(post))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        post = Dashboard::Post.create! valid_attributes
        patch dashboard_post_url(post), params: { dashboard_post: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested dashboard_post' do
      post = Dashboard::Post.create! valid_attributes
      expect do
        delete dashboard_post_url(post)
      end.to change(Dashboard::Post, :count).by(-1)
    end

    it 'redirects to the dashboard_posts list' do
      post = Dashboard::Post.create! valid_attributes
      delete dashboard_post_url(post)
      expect(response).to redirect_to(dashboard_posts_url)
    end
  end
end
