default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  user: <%= ENV.fetch("DATABASE_USER") { "svck" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "Password123" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 50 } %>

development:
  <<: *default
  database: web_development
test:
  <<: *default
  database: web_test
production:
  <<: *default
  database: web