// This file is auto-generated by @hey-api/openapi-ts

export const postSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        content: {
            type: 'string'
        },
        user: {
            type: 'object',
            properties: {
                id: {
                    type: 'string',
                    format: 'uuid'
                },
                email: {
                    type: 'string',
                    format: 'email'
                }
            },
            required: ['id', 'email']
        },
        visibility: {
            type: 'string',
            enum: ['everyone', 'friends_only', 'nobody']
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        parent: {
            type: 'string',
            nullable: true
        },
        comments_count: {
            type: 'integer'
        },
        comments: {
            type: 'array',
            items: {
                type: 'object',
                '$ref': '#/components/schemas/comment',
                required: ['id', 'content', 'user', 'visibility', 'created_at', 'comments_count']
            }
        },
        model: {
            type: 'string',
            'x-nullable': true
        }
    },
    required: ['id', 'content', 'user', 'visibility', 'created_at', 'comments_count']
} as const;

export const commentSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        content: {
            type: 'string'
        },
        user: {
            type: 'object',
            properties: {
                id: {
                    type: 'string',
                    format: 'uuid'
                },
                email: {
                    type: 'string',
                    format: 'email'
                }
            },
            required: ['id', 'email']
        },
        visibility: {
            type: 'string',
            enum: ['everyone', 'friends_only', 'nobody']
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        parent: {
            type: 'string',
            nullable: true
        },
        comments_count: {
            type: 'integer'
        },
        comments: {
            type: 'array',
            items: {
                type: 'object',
                '$ref': '#/components/schemas/comment',
                required: ['id', 'content', 'user', 'visibility', 'created_at', 'comments_count']
            }
        },
        model: {
            type: 'string',
            'x-nullable': true
        }
    },
    required: ['id', 'content', 'user', 'visibility', 'created_at', 'comments_count']
} as const;